#!/bin/sh
# ---------------------------------------------------------------------------
# scripts/pin-images.sh
#
# Resolves the floating image tags used in this repository to their current
# sha256 digests and prints lines suitable for copy-pasting into Dockerfiles
# and docker-compose.yml.
#
# Usage:
#   ./scripts/pin-images.sh            # prints lines to stdout
#   ./scripts/pin-images.sh --update   # (reserved for future automation)
#
# Requires: docker (local daemon or remote DOCKER_HOST). Requires network
# access to the registries for each image. Runs `docker pull` then reads
# RepoDigests.
# ---------------------------------------------------------------------------
set -eu

IMAGES="
postgres:17
python:3.12-slim
node:22-alpine
alpine:3.21
"

resolve() {
    image="$1"
    docker pull --quiet "${image}" >/dev/null
    digest="$(docker inspect --format='{{index .RepoDigests 0}}' "${image}")"
    printf '%s  # pinned from %s\n' "${digest}" "${image}"
}

echo "# Generated by scripts/pin-images.sh at $(date -u +%FT%TZ)"
echo "# Copy the appropriate '<repo>@sha256:<digest>' line into each FROM / image: reference."
echo

for img in ${IMAGES}; do
    [ -z "${img}" ] && continue
    resolve "${img}"
done